# .github/workflows/run_worker.yml

name: Run Promotion Worker

on:
  # This is the "cron job" trigger
  schedule:
    # This runs the job every 10 minutes
    - cron: '*/10 * * * *'
  
  # This line lets you run it manually from the "Actions" tab on GitHub
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest # Use a standard Linux server
    
    steps:
      # 1. Get your code from the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your Python version

      # 3. Install your Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r microservices/requirements.txt
      
      # 4. Run your worker script
      - name: Run worker
        env:
          # This pulls the database URL from your GitHub secrets
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python microservices/worker.py